Add server-side filter
wavefrontHQ/wavefront-jaxrs-sdk-java pull request #9
Opened 2018-11-29 04:56 UTC by song-hao

2018-12-10 12:49 UTC, srujann requested changes
There is one missed metric (total_time) and some nits.

2018-12-10 12:49 UTC, srujann commented on src/main/java/com/wavefront/sdk/jaxrs/server/WavefrontJaxrsServerFilter.java
> +                               @Nullable Tracer tracer) {
not aligned

2018-12-10 12:49 UTC, srujann commented on src/main/java/com/wavefront/sdk/jaxrs/server/WavefrontJaxrsServerFilter.java
> +
Nit: reduce blank lines where ever possible, to save screen real estate.

2018-12-10 12:49 UTC, srujann commented on src/main/java/com/wavefront/sdk/jaxrs/server/WavefrontJaxrsServerFilter.java
> +       * 1) <prefix>.response.errors.aggregated_per_source (Counter)
Nit: update the comments to jaxrs.server similar to other comments

2018-12-10 12:49 UTC, srujann commented on src/main/java/com/wavefront/sdk/jaxrs/server/WavefrontJaxrsServerFilter.java
> +          completeTagsMap), apiLatency);
```suggestion
          completeTagsMap), apiLatency);
          
      /**
       * total time spent counter: jaxrs.server.response.api.v2.alert.summary.GET.200.total_time
       */
      wfJaxrsReporter.incrementCounter(new MetricName(responseMetricKey + ".total_time",
          completeTagsMap), apiLatency);
```

2018-12-12 10:13 UTC, srujann approved these changes
LGTM

2018-12-12 23:06 UTC, sushantdewan123 requested changes

2018-12-12 23:06 UTC, sushantdewan123 commented on src/test/java/com/wavefront/sdk/jaxrs/JaxrsAppReporterTest.java
> +//    testCreate();
Why are these tests commented? by mistake?

2018-12-12 23:10 UTC, sushantdewan123 approved these changes
LGTM

2019-02-04 22:22 UTC, merged